from setuptools import setup, find_packages

VERSION = '0.3.0'
DESCRIPTION = 'A Python tool for video-based traffic analytiscs'
LONG_DESCRIPTION = ''

setup(
    name="dnt",
    version=VERSION,
    description=DESCRIPTION,
    long_description=LONG_DESCRIPTION,
    author="Zhenyu Wang",
    author_email="wonstran@hotmail.com",
    license='MIT',
    packages=find_packages(include=("*.yaml")),
    keywords=('traffic', 'vehicle', 'trajectory', 'safety'),
    url = 'https://its.cutr.usf.edu/dnt/',
    classifiers= [
        "Development Status :: 3 - Alpha",
        "Intended Audience :: End Users/Desktop",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
    ],
    install_requires = [
        'torch',
        'torchvision', 
        'torchaudio',
        'ultralytics>=8.2',
        'cython',
        'cython_bbox',
        'easydict',
        'faiss-cpu',
        'faiss-gpu',
        'filterpy',
        'gdown',
        'geopandas',
        'h5py',
        'lap',
        'loguru',
        'matplotlib',
        'motmetrics',
        'ninja',
        'numpy',
        'numpy_indexed',
        'opencv-contrib-python',
        'opencv-python',
        'pandas',
        'Pillow',
        'prettytable',
        'pycocotools',
        'pyyaml',
        'scikit-image',
        'scikit-learn',
        'scipy',
        'shapely',
        'sympy',
        'tabulate',
        'tensorboard',
        'termcolor',
        'thop',
        'tqdm',
        'vidgear',
        'yacs',
    ],
    python_requires='>=3.9',
    include_package_data=True,
)